### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'split')     at Object.<anonymous> (.../node_modules/officeparser/officeParser.js:719:115)

### ISSUE THREAD

**Issue by jeanmachuca** [harshankur/officeParser#46]
# Uncaught TypeError Error given when try to test officeParser in node shell

```shell
Uncaught TypeError: Cannot read properties of undefined (reading 'split')     at Object.<anonymous> (.../node_modules/officeparser/officeParser.js:719:115)
```

# Steps to reproduce:

```typescript

// TypeScript file parser.ts
import officeParser from "officeparser";

const parseFile = async (filePath: string): Promise<string> => {
  let data = "";
  try {
    data = await officeParser.parseOfficeAsync(filePath);
    return data;
  } catch (err) {
    console.error("Error parsing the file:", err);
  }
  return data;
};

export default parseFile;
```

2.- Transpile to JavaScript:

```shell
npx tsc
```

3.- Start node:

```shell
node 
```

4.- In the node shell, try to require the parser.js :

```shell
const parser = require ("./parser")
```

5.- Result:
```shell 
Welcome to Node.js v22.9.0.
Type ".help" for more information.
> require ("./src/parser")
Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at Object.<anonymous> (.../node_modules/officeparser/officeParser.js:719:115)
```

# Proposed solution:

It looks like the problem raises in the following line:

https://github.com/harshankur/officeParser/blob/8f2e4be7f156aed1de2d7f076407d681d69e6eb7/officeParser.js#L719

It seems like it should be added an optional chaining operator for each arguments parameter.

```typescript
if ((process.argv[0]?.split('/').pop() == "node" || process.argv[0]?.split('/').pop() == "npx") && (process.argv[1]?.split('/').pop() == "officeParser.js" || process.argv[1]?.split('/').pop().toLowerCase() == "officeparser"))
```

# Expected result after solution is applied:

```shell
$ node 
Welcome to Node.js v22.9.0.
Type ".help" for more information.
> let parse = require ("./src/parser")
undefined
> parse
{ default: [Function: parseFile] }
> 
```

I can make a PR if you would like to add this solution.
Thank you.

**Comment by harshankur** [comment]
Hi @jeanmachuca, thank you for that.
I think I already fixed this in the new version 5.0.0. If not, please create a PR for v5.
